const LANG = {
  fr: {
    online: "En ligne", offline: "Hors ligne", install: "Installer",
    losses: "Pertes du mois", weight: "Poids", stock: "Valeur du stock",
    active_products: "Produits actifs", recipes: "Recettes", last_production: "Dernière prod",
    assistant: "Assistant vocal", speak: "Parler", stop: "Arrêter",
    record_loss: "Saisir une perte", product: "Produit", quantity: "Quantité", unit: "Unité",
    unit_hint:"Unité (kg, L, pcs)", unit_price:"Prix unitaire (€)", reason:"Motif",
    zone_hint:"Zone (FROID, ECO, PATISSERIE…)", save:"Enregistrer",
    inv_daily_active:"Inventaire journalier (actif)", control:"Contrôle", entry:"Entrée", exit:"Sortie",
    new_product:"Nouveau produit", comment_opt:"Commentaire (optionnel)",
    inv_month_zone:"Inventaire mensuel par zone", create_open_zone_sheet:"Créer / Ouvrir feuille zone",
    losses_month_detail:"Pertes du mois — détail produits", value_eur:"Valeur (€)", last_loss:"Dernière perte",
    search_recipe:"Rechercher une recette…", recipe_name:"Recette", category:"Catégorie",
    base_portions:"Portions base", cost_per_portion:"Coût/portion", open:"Ouvrir",
    produce:"Produire", ingredient:"Ingrédient", qty:"Qté"
  },
  en: {
    online: "Online", offline: "Offline", install: "Install",
    losses: "Monthly losses", weight: "Weight", stock: "Stock value",
    active_products: "Active products", recipes: "Recipes", last_production: "Last production",
    assistant: "Voice assistant", speak: "Speak", stop: "Stop",
    record_loss: "Record a loss", product: "Product", quantity: "Quantity", unit:"Unit",
    unit_hint:"Unit (kg, L, pcs)", unit_price:"Unit price (€)", reason:"Reason",
    zone_hint:"Zone (COLD, STORE, PASTRY…)", save:"Save",
    inv_daily_active:"Daily inventory (active)", control:"Control", entry:"Entry", exit:"Exit",
    new_product:"New product", comment_opt:"Comment (optional)",
    inv_month_zone:"Monthly inventory by zone", create_open_zone_sheet:"Create / Open zone sheet",
    losses_month_detail:"Monthly losses — products detail", value_eur:"Value (€)", last_loss:"Last loss",
    search_recipe:"Search a recipe…", recipe_name:"Recipe", category:"Category",
    base_portions:"Base portions", cost_per_portion:"Cost/portion", open:"Open",
    produce:"Produce", ingredient:"Ingredient", qty:"Qty"
  },
  it: {
    online: "Online", offline: "Offline", install: "Installa",
    losses: "Perdite del mese", weight: "Peso", stock: "Valore stock",
    active_products: "Prodotti attivi", recipes: "Ricette", last_production: "Ultima produzione",
    assistant: "Assistente vocale", speak: "Parla", stop: "Ferma",
    record_loss: "Registrare una perdita", product: "Prodotto", quantity: "Quantità", unit:"Unità",
    unit_hint:"Unità (kg, L, pz)", unit_price:"Prezzo unitario (€)", reason:"Motivo",
    zone_hint:"Zona (FREDDO, ECONOMATO, PASTICCERIA…)", save:"Salva",
    inv_daily_active:"Inventario giornaliero (attivo)", control:"Controllo", entry:"Entrata", exit:"Uscita",
    new_product:"Nuovo prodotto", comment_opt:"Commento (opzionale)",
    inv_month_zone:"Inventario mensile per zona", create_open_zone_sheet:"Crea / Apri foglio zona",
    losses_month_detail:"Perdite del mese — dettaglio prodotti", value_eur:"Valore (€)", last_loss:"Ultima perdita",
    search_recipe:"Cerca una ricetta…", recipe_name:"Ricetta", category:"Categoria",
    base_portions:"Porzioni base", cost_per_portion:"Costo/porzione", open:"Apri",
    produce:"Produci", ingredient:"Ingrediente", qty:"Qtà"
  },
  es: {
    online: "Conectado", offline: "Sin conexión", install: "Instalar",
    losses: "Pérdidas del mes", weight: "Peso", stock: "Valor del stock",
    active_products: "Productos activos", recipes: "Recetas", last_production: "Última producción",
    assistant: "Asistente de voz", speak: "Hablar", stop: "Parar",
    record_loss: "Registrar una pérdida", product: "Producto", quantity: "Cantidad", unit:"Unidad",
    unit_hint:"Unidad (kg, L, uds)", unit_price:"Precio unitario (€)", reason:"Motivo",
    zone_hint:"Zona (FRÍO, ECO, PASTELERÍA…)", save:"Guardar",
    inv_daily_active:"Inventario diario (activo)", control:"Control", entry:"Entrada", exit:"Salida",
    new_product:"Producto nuevo", comment_opt:"Comentario (opcional)",
    inv_month_zone:"Inventario mensual por zona", create_open_zone_sheet:"Crear / Abrir hoja de zona",
    losses_month_detail:"Pérdidas del mes — detalle productos", value_eur:"Valor (€)", last_loss:"Última pérdida",
    search_recipe:"Buscar una receta…", recipe_name:"Receta", category:"Categoría",
    base_portions:"Porciones base", cost_per_portion:"Coste/porción", open:"Abrir",
    produce:"Producir", ingredient:"Ingrediente", qty:"Cant."
  }
};